// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:summary_ai_app/model/a_i_response.dart';
import 'package:summary_ai_app/model/difficulty_set.dart';
import 'package:summary_ai_app/model/mcq_question.dart';
import 'package:summary_ai_app/model/msq_question.dart';
import 'package:summary_ai_app/model/question_answer.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AIResponseAdapter());
    registerAdapter(DifficultySetAdapter());
    registerAdapter(McqQuestionAdapter());
    registerAdapter(MsqQuestionAdapter());
    registerAdapter(QuestionAnswerAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AIResponseAdapter());
    registerAdapter(DifficultySetAdapter());
    registerAdapter(McqQuestionAdapter());
    registerAdapter(MsqQuestionAdapter());
    registerAdapter(QuestionAnswerAdapter());
  }
}
